SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1400

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.9
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS*ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_SPEED = 260
PLAYER_ROTATE_SPEED = 200
FIRE_RATE = 0.35

PROJECTILE_RADIUS = 5
PROJECTILE_SPEED = 500
